# Originally inspired by Cloudflare Wrangler
# https://github.com/cloudflare/wrangler2/blob/main/.github/workflows/prereleases.yml

name: Release - Beta

on:
  pull_request:
    types: [labeled]
    branches:
      - main
jobs:
  prerelease:
    if: |
      github.repository_owner == 'badass-courses' &&
      contains(github.event.pull_request.labels.*.name, 'ðŸš€ autorelease')
    name: Build & Publish a beta release to NPM
    runs-on: ubuntu-latest
    env:
      MOTION_PLUS_TOKEN: ${{ secrets.MOTION_PLUS_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use PNPM
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install NPM Dependencies
        run: pnpm install

      - name: Modify package.json version
        run: node .github/version-script-beta.js

      - name: Authenticate to NPM
        run:
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN
          }}" > cli/.npmrc

      - name: Publish Beta to NPM
        run: pnpm pub:beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: cli

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package-create-course-app@${{
            steps.package-version.outputs.current-version }}-pr-${{
            github.event.number }} # encode the PR number into the artifact name
          path: cli/dist/index.js
